### ISSUE TITLE
activate filter gte in report list endpoint

### ISSUE THREAD

**Issue by rogergithub3** [tesla-ce/core#109]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xbaro** [comment]
![image](https://user-images.githubusercontent.com/1412358/147555060-6c5b1611-7754-44fd-a2fc-f91514b1dddf.png)

**Comment by xbaro** [comment]
Implemented filters for each option with __lte and __gte. In addition, a custom filter with name "level" allows to filter for all types of levels. In this case, it is possible also to use __lte and __gte.
