### ISSUE TITLE
add filters in endpoint api/v2/institution/1/send

### ISSUE THREAD

**Issue by rogergithub3** [tesla-ce/core#110]
**Describe the bug**
It is necessary to activate filters in this endpoint:
api/v2/institution/1/send/?description=miop&offset=0&limit=10

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xbaro** [comment]
Enabled basic filters over fields intitution and description. Maybe some specific filters may be defined.
