### ISSUE TITLE
it is not generated deploy tesla_tks_provider.yml when it is registered.

### ISSUE THREAD

**Issue by rogergithub3** [tesla-ce/core#118]
**Describe the bug**
it is not generated deploy tesla_tks_provider.yml when it is registered. Also, secrets are not created.

**To Reproduce**
1. tesla_ce register_provider -> tks_ks

**Comment by xbaro** [comment]
Cannot reproduce this error. The yml file is generated and secrets also.

**Comment by rogergithub3** [comment]
yeap
