### ISSUE TITLE
Error 500 when get activities of user is not leaner

### ISSUE THREAD

**Issue by rogergithub3** [tesla-ce/core#122]
**Describe the bug**
API returns error code 500 when get activites of user is not leaner

**To Reproduce**
1. Login to dashboard with global admin.
2. Check console.log

**Expected behavior**
Returns code 200 response with empty activities.

**Screenshots**
![Screenshot_2021-12-27_11-44-27](https://user-images.githubusercontent.com/26788912/147464502-f7442e1c-604b-4f92-a79b-9013006c8a0d.png)

**Comment by xbaro** [comment]
Fixed.
